// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blcahjcuivscnlfqdutk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsY2FoamN1aXZzY25sZnFkdXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NzM5MTEsImV4cCI6MjA1NjE0OTkxMX0.iEG6y3dmu1bvsAx_NxjpZIqu5hvsCaTFySEXfB_u4Q8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);