// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qivbcpiqqpzuexvooqba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpdmJjcGlxcXB6dWV4dm9vcWJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyNDIwOTYsImV4cCI6MjA1NDgxODA5Nn0.284YhlnBWGjJlgUUIlHtuXVRuMtSvFgNcFuK9LKD154";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);